name: Build and Release RStudio Server SIF

on:
  push:
    tags:
      - 'v*'              # Trigger on version tags like v1.0, v2.5, etc.
  workflow_dispatch:

permissions:
  contents: write       # Required for creating releases and uploading assets

jobs:
  build-sif:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apptainer (PPA)
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build SIF
        run: |
          apptainer build rstudio_server.sif rstudio-server.def

      - name: Upload SIF as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: rstudio_server.sif
          path: rstudio_server.sif

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: rstudio_server.sif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
